apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: {{ .Release.Namespace }}
spec:
  externalAccess:
    enabled: true
  keycloakDeploymentSpec:
    imagePullPolicy: IfNotPresent
  postgresDeploymentSpec:
    imagePullPolicy: IfNotPresent
  instances: 1
