apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: cert-manager
  namespace: {{ .Release.Namespace }}
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: GCPProviderSpec
    predefinedRoles:
    - roles/dns.admin
  secretRef:
    name: acme-gcp-credentials
    namespace: {{ .Release.Namespace }}
  serviceAccountNames:
  - cert-manager
