{{ if .Values.manageNamespaceAndOperatorGroup }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-storage
  namespace: {{ .Release.Namespace }}
spec:
  targetNamespaces:
  - openshift-storage
{{ end }}
