apiVersion: v1
kind: Secret
metadata:
  name: quay-registry-config-bundle
  namespace: {{ .Release.Namespace }}
stringData:
  config.yaml: |
    # List of available configuration options can be found at:
    # https://github.com/quay/quay/blob/master/util/config/schema.py
    SUPER_USERS:
    - admin
    AUTHENTICATION_TYPE: Database
    DISTRIBUTED_STORAGE_CONFIG:
      default:
      - RHOCSStorage
      - hostname: {{ .Values.storageHostname }}
        port: '{{ .Values.storagePort }}'
        is_secure: {{ .Values.storageIsSecure }}
        access_key: '{{ .Values.storageAccessKey }}'
        secret_key: '{{ .Values.storageSecretKey }}'
        bucket_name: '{{ .Values.storageBucketName }}'
        storage_path: /quay/storage
    DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
    DISTRIBUTED_STORAGE_PREFERENCE:
    - default
    FEATURE_DIRECT_LOGIN: true
    # Create organization and repo automatically
    CREATE_NAMESPACE_ON_PUSH: true
    CREATE_ORGANIZATION_ON_PUSH: true
    # Allow creating the first user via API call, see also:
    # As an admin, I want an API to create first user, so I can automate deployment
    # https://issues.redhat.com/browse/PROJQUAY-1926
    FEATURE_USER_INITIALIZE: true
