apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: win-webserver
  namespace: {{ .Release.Namespace }}
spec:
  port:
    targetPort: 80
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: win-webserver
