apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: acme-aws
  namespace: {{ .Release.Namespace }}
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - action:
      - route53:GetChange
      effect: Allow
      resource: arn:aws:route53:::change/*
    - action:
      - route53:ChangeResourceRecordSets
      - route53:ListResourceRecordSets
      effect: Allow
      resource: arn:aws:route53:::hostedzone/*
    - action:
      - route53:ListHostedZonesByName
      effect: Allow
      resource: "*"
  secretRef:
    name: acme-aws-credentials
    namespace: {{ .Release.Namespace }}
  serviceAccountNames:
  - cert-manager
