apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-hec
  namespace: {{ .Release.Namespace }}
spec:
  port:
    targetPort: 8088
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: splunk-{{ .Release.Name }}-standalone-service
