apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: bpfman
  namespace: {{ .Release.Namespace }}
spec:
{{- with .Values.subscriptionChannel }}
  channel: {{ . }}
{{- end }}
  installPlanApproval: {{ .Values.subscriptionApproval }}
  name: bpfman-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- with .Values.subscriptionStartingCsv }}
  startingCSV: {{ . }}
{{- end }}
