apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db
  namespace: {{ .Release.Namespace }}
stringData:
  username: '{{ .Values.databaseUsername }}'
  password: '{{ .Values.databasePassword }}'
{{- if .Values.databaseAdminPassword }}
  admin_password: '{{ .Values.databaseAdminPassword }}'
{{- end }}
