storageHostname: minio-api-quay-enterprise-minio.apps.mycluster2.example.com
storagePort: '443'
storageIsSecure: true
storageAccessKey: admin
storageSecretKey: ''
storageBucketName: mybucket1

quayReplicas: 2
