apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: multicluster-global-hub-operator-rh
  namespace: {{ .Release.Namespace }}
spec:
{{- with .Values.subscriptionChannel }}
  channel: {{ . }}
{{- end }}
  installPlanApproval: {{ .Values.subscriptionApproval }}
  name: multicluster-global-hub-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- with .Values.subscriptionStartingCsv }}
  startingCSV: {{ . }}
{{- end }}
