apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: grafana-sa
  name: {{ .Release.Name }}-sa-token-static
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/service-account-token
