apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-cluster-logging-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-cluster-logging-view
subjects:
- kind: ServiceAccount
  name: grafana-sa
  namespace: {{ .Release.Namespace }}
