apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cluster-kube-descheduler-operator
  namespace: {{ .Release.Namespace }}
spec:
  targetNamespaces:
  - {{ .Release.Namespace }}
