kind: ConfigMap
apiVersion: v1
metadata:
  name: keycloak-entrypoint
  namespace: {{ .Release.Namespace }}
data:
  keycloak-entrypoint.sh: |
    #!/usr/bin/env bash

    CA_DIR=/mnt/trust-ca
    TRUSTSTORE_DIR=/mnt/truststore

    echo "Building the truststore file..."

    cp /etc/pki/java/cacerts ${TRUSTSTORE_DIR}/keycloak-truststore.jks
    chmod +w ${TRUSTSTORE_DIR}/keycloak-truststore.jks

    IFS='
    '
    for cert in `ls ${CA_DIR}`; do
        echo "Importing ${cert} into the truststore file..."
        keytool -importcert -file ${CA_DIR}/${cert} -keystore ${TRUSTSTORE_DIR}/keycloak-truststore.jks -storepass changeit -alias ${cert} -noprompt
    done

    echo "Truststore file built, starting Keycloak ..."
    "/opt/keycloak/bin/kc.sh" "$@" --spi-truststore-file-file=${TRUSTSTORE_DIR}/keycloak-truststore.jks --spi-truststore-file-password=changeit --spi-truststore-file-hostname-verification-policy=WILDCARD
