kyverno:
  policyReportsCleanup:
    securityContext:
      runAsUser: null
      runAsGroup: null
      runAsNonRoot: true
      privileged: false
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
