kyverno:
  admissionController:
    # Create serviceMonitor object so that OpenShift can auto-discover
    # metric endpoints and start collecting metrics automatically
    # See also https://kyverno.io/docs/monitoring/
    serviceMonitor:
      enabled: true
    # Tracing is disabled by default and depending on the backend the associated
    # cost can be significant.
    # See also https://kyverno.io/docs/tracing/
    tracing:
      enabled: false
      address: tempo-tempostack-distributor.tempostack.svc
      port: 4317
  backgroundController:
    serviceMonitor:
      enabled: true
    tracing:
      enabled: false
      address: tempo-tempostack-distributor.tempostack.svc
      port: 4317
  cleanupController:
    serviceMonitor:
      enabled: true
    tracing:
      enabled: false
      address: tempo-tempostack-distributor.tempostack.svc
      port: 4317
  reportsController:
    serviceMonitor:
      enabled: true
    tracing:
      enabled: false
      address: tempo-tempostack-distributor.tempostack.svc
      port: 4317
  policyReportsCleanup:
    securityContext:
      runAsUser: null
      runAsGroup: null
      runAsNonRoot: true
      privileged: false
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
