apiVersion: v1
kind: Secret
metadata:
  name: secrets-rhdh
  namespace: {{ .Release.Namespace }}
stringData:
  KEYCLOAK_CLIENT_SECRET: '{{ .Values.keycloakClientSecret }}'
  BACKEND_SECRET: '{{ .Values.backstageBackendSecret }}'
  SESSION_SECRET: '{{ .Values.backstageSessionSecret }}'
  # TODO Configure trusted CA certificate
  NODE_TLS_REJECT_UNAUTHORIZED: '0'
