apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-external-cluster-details
  namespace: {{ .Release.Namespace }}
stringData:
  external_cluster_details: {{ toYaml .Values.externalClusterDetails | nindent 12 }}
