apiVersion: v1
kind: Secret
metadata:
  name: loki-s3
  namespace: {{ .Release.Namespace }}
stringData:
  access_key_id: '{{ .Values.s3AccessKeyId }}'
  access_key_secret: '{{ .Values.s3SecretAccessKey }}'
  bucketnames: {{ .Values.s3BucketNames }}
  endpoint: {{ .Values.s3Endpoint }}
  region: {{ .Values.s3Region }}
