apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: aws-efs-csi-driver-operator
  namespace: openshift-cluster-csi-drivers
spec:
{{- if .Values.subscriptionChannel }}
  channel: {{ .Values.subscriptionChannel }}
{{- end }}
  installPlanApproval: {{ .Values.subscriptionChannel }}
  name: aws-efs-csi-driver-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
