apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: power-monitoring-operator
  namespace: openshift-operators
spec:
{{- if .Values.subscriptionChannel }}
  channel: {{ .Values.subscriptionChannel }}
{{- end }}
  installPlanApproval: {{ .Values.subscriptionApproval }}
  name: power-monitoring-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
