apiVersion: v1
kind: Secret
metadata:
  name: s3-creds
  namespace: {{ .Release.Namespace }}
stringData:
  endpoint: {{ .Values.s3Endpoint }}
  bucket: {{ .Values.s3Bucket }}
  access_key_id: '{{ .Values.s3AccessKeyId }}'
  access_key_secret: '{{ .Values.s3AccessKeySecret }}'
