apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: tempostack
  namespace: {{ .Release.Namespace }}
spec:
  storage:
    secret:
      name: s3-creds
      type: s3
  storageSize: 1Gi
  resources:
    total:
      limits:
        memory: 2Gi
        cpu: '2'
  template:
    queryFrontend:
      jaegerQuery:
        enabled: true
