apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhdh
  namespace: rhdh-operator
spec:
{{- with .Values.subscriptionChannel }}
  channel: {{ . }}
{{- end }}
  installPlanApproval: {{ .Values.subscriptionApproval }}
  name: rhdh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- with .Values.subscriptionStartingCsv }}
  startingCSV: {{ . }}
{{- end }}
