apiVersion: v1
kind: Service
metadata:
  name: webhook-receiver
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: webhook-receiver
  ports:
  - name: http-8080
    port: 8080
    protocol: TCP
