apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: netobserv-operator
  namespace: {{ .Release.Namespace }}
spec:
{{- if .Values.subscriptionChannel }}
  channel: {{ .Values.subscriptionChannel }}
{{- end }}
  installPlanApproval: {{ .Values.subscriptionApproval }}
  name: netobserv-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
