apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-rootdisk
  namespace: {{ .Release.Namespace }}
spec:
  dataSourceRef:
    apiGroup: cdi.kubevirt.io
    kind: VolumeImportSource
    name: {{ .Release.Name }}-rootdisk
  accessModes: {{ toYaml .Values.machineRootDiskAccessModes | nindent 2 }}
  resources:
    requests:
      storage: '{{ .Values.machineRootDiskCapacity }}'
{{- if gt (len .Values.machineRootDiskStorageClassName) 0 }}
  storageClassName: {{ .Values.machineRootDiskStorageClassName }}
{{- end }}
  volumeMode: {{ .Values.machineRootDiskVolumeMode }}
