apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cloudinit
  namespace: {{ .Release.Namespace }}
stringData:
  userdata: |
    #cloud-config
    user: '{{ .Values.machineUserName }}'
    password: '{{ .Values.machineUserPassword }}'
    chpasswd:
      expire: false
    ssh_pwauth: true
    ssh_authorized_keys:
    - '{{ .Values.machineSshAuthorizedKey }}'
