apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  liveUpdateFeatures:
    cpu: {}
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/domain: {{ .Release.Name }}
        kubevirt.io/size: small
        vm.kubevirt.io/name: {{ .Release.Name }}
        os.template.kubevirt.io/fedora37: 'true'
        flavor.template.kubevirt.io/small: 'true'
        workload.template.kubevirt.io/server: 'true'
    spec:
      {{- with .Values.machineNodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/baremetal
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: cloudinitdisk
          - bootOrder: 1
            disk:
              bus: virtio
            name: rootdisk
          interfaces:
          - masquerade: {}
            model: virtio
            name: default
          # CPU hotplug doesn't work with multiqueue virtio-net at this time
          networkInterfaceMultiqueue: false
          rng: {}
        machine:
          type: pc-q35-rhel8.3.0
        resources:
          requests:
            memory: 2Gi
      evictionStrategy: {{ .Values.machineEvictionStrategy }}
      hostname: {{ .Release.Name }}
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
      - cloudInitNoCloud:
          secretRef:
            name: {{ .Release.Name }}-cloudinit
        name: cloudinitdisk
      - dataVolume:
          name: {{ .Release.Name }}-rootdisk
        name: rootdisk
