apiVersion: cdi.kubevirt.io/v1beta1
kind: VolumeImportSource
metadata:
  name: {{ .Release.Name }}-rootdisk
  namespace: {{ .Release.Namespace }}
spec:
  source:
{{- with .Values.machineImageHttpUrl }}
    http:
      url: {{ . }}
      certConfigMap: {{ $.Release.Name }}-trusted-ca-bundle
{{- end }}
{{- with .Values.machineImageRegistryUrl }}
    registry:
      url: {{ . }}
      # Take advantage of the OpenShift pull secret which is required
      # to pull container images from the Red Hat registry.
      pullMethod: node
{{- end }}
