kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: etcd-backup
  namespace: openshift-etcd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  volumeMode: Filesystem
