apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: mtv-operator
  namespace: openshift-mtv
spec:
  channel: {{ .Values.subscriptionChannel }}
  installPlanApproval: {{ .Values.subscriptionApproval }}
  name: mtv-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
