apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sysdig-oss-scc
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  - hostaccess
  - hostmount-anyuid
  - hostnetwork
  - nonroot
  - privileged
  - restricted
  resources:
  - securitycontextconstraints
  verbs:
  - use
