apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: compliance-operator
  namespace: openshift-compliance
spec:
{{- with .Values.subscriptionChannel }}
  channel: {{ . }}
{{- end }}
  installPlanApproval: {{ .Values.subscriptionApproval }}
  name: compliance-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
