apiVersion: v1
kind: Secret
metadata:
  name: case-management-creds
  namespace: {{ .Release.Namespace }}
data:
  username: '{{ .Values.caseManagementUsername }}'
  password: '{{ .Values.caseManagementPassword }}'
