apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: must-gather-operator
  namespace: {{ .Release.Namespace }}
spec:
{{- if .Values.subscriptionChannel }}
  channel: {{ .Values.subscriptionChannel }}
{{- end }}
  installPlanApproval: {{ .Values.subscriptionApproval }}
  name: must-gather-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
