apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: loki-netobserv-tenant
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: loki-netobserv-tenant
subjects:
- kind: ServiceAccount
  name: flowlogs-pipeline
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: netobserv-plugin
  namespace: {{ .Release.Namespace }}
