apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  annotations:
    uninstall.ocs.openshift.io/cleanup-policy: {{ .Values.uninstallCleanUpPolicy }}
    uninstall.ocs.openshift.io/mode: {{ .Values.uninstallMode }}
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  enableCephTools: true
{{- if or .Values.encryptionClusterWide .Values.encryptionKmsEnable }}
  encryption:
{{- if .Values.encryptionClusterWide }}
    clusterWide: true
{{- end }}
{{- if .Values.encryptionKmsEnable }}
    kms:
      enable: true
{{- end }}
{{- end }}
  monPVCTemplate:
    metadata: {}
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: '{{ .Values.monPVCTemplate.storageCapacity }}'
      storageClassName: {{ .Values.monPVCTemplate.storageClassName }}
      volumeMode: Filesystem
    status: {}
  nfs:
    enable: true
  storageDeviceSets:
  - config: {}
    count: {{ .Values.storageDeviceSets.count }}
    dataPVCTemplate:
      metadata: {}
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: '{{ .Values.storageDeviceSets.storageCapacity }}'
        storageClassName: {{ .Values.storageDeviceSets.storageClassName }}
        volumeMode: Block
      status: {}
    name: ocs-deviceset
    placement: {}
    portable: true
    preparePlacement: {}
    replica: {{ .Values.storageDeviceSets.replica }}
    resources: {}
