apiVersion: v1
kind: Secret
metadata:
  name: certificate-authority-key-pair
  namespace: {{ .Release.Namespace }}
stringData:
  tls.crt: |
    {{- .Values.issuerTlsCrt | nindent 4 }}
  tls.key: |
    {{- .Values.issuerTlsKey | nindent 4 }}
