apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  annotations:
    kubevirt.kubevirt.io/jsonpatch: |-
      [
        {
          "op":"add",
          "path":"/spec/configuration/developerConfiguration/featureGates/-",
          "value":"VMLiveUpdateFeatures"
        }
      ]
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
spec:
  evictionStrategy: LiveMigrateIfPossible
  infra: {}
  workloads:
    nodePlacement:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/baremetal
  workloadUpdateStrategy:
    workloadUpdateMethods:
    - LiveMigrate
