apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  name: stackrox-secured-cluster-services
  namespace: {{ .Release.Namespace }}
spec:
  admissionControl:
    # Enable preventive policy enforcement for object creations.
    # The default value is false.
    listenOnCreates: true
    # Enable monitoring and enforcement for Kubernetes events, such as port-forward and exec events.
    # The default value is true.
    listenOnEvents: true
    # Enable preventive policy enforcement for object updates.
    # It will not have any effect unless Listen On Creates is set to true as well.
    # The default value is false.
    listenOnUpdates: true
  sensor:
{{- if eq .Values.deploymentMode "dev" }}
    resources:
      limits:
        cpu: 4000m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 500Mi
{{- end }}
  centralEndpoint: {{ .Values.centralHost }}:443
  clusterName: {{ .Values.clusterName }}
  perNode:
    collector:
      collection: KernelModule
      imageFlavor: Regular
    taintToleration: TolerateTaints
  customize:
    envVars:
      # Set log level for Sensor, Admission Controller, Collector. Allowed values are debug, info, ...
      - name: LOGLEVEL
        value: '{{ .Values.logLevel }}'
{{- if gt (len .Values.additionalTrustedCa) 0 }}
  tls:
    additionalCAs:
      - name: custom_trusted_ca
        content: |
          {{- .Values.additionalTrustedCa | nindent 10 }}
{{- end }}
