{{- if gt (len .Values.centralDbPassword) 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: central-db-password
  namespace: {{ .Release.Namespace }}
stringData:
  password: '{{ .Values.centralDbPassword }}'
{{- end }}
