{{- if gt (len .Values.centralAdminPasswordPlain) 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: central-htpasswd
  namespace: {{ .Release.Namespace }}
stringData:
  password: {{ .Values.centralAdminPasswordPlain }}
  htpasswd: admin:{{ .Values.centralAdminPasswordHash }}
{{- end }}
