{{- if gt (len .Values.centralDefaultTlsCrt) 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: central-default-tls-cert
  namespace: {{ .Release.Namespace }}
data:
  tls.crt: '{{ .Values.centralDefaultTlsCrt | b64enc }}'
  tls.key: '{{ .Values.centralDefaultTlsKey | b64enc }}'
type: kubernetes.io/tls
{{- end }}
