{{- if gt (len .Values.scannerDbPassword) 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: scanner-db-password
  namespace: {{ .Release.Namespace }}
stringData:
  password: '{{ .Values.scannerDbPassword }}'
{{- end }}
