apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  name: stackrox-central-services
  namespace: {{ .Release.Namespace }}
spec:
  central:
{{- if gt (len .Values.centralAdminPasswordPlain) 0 }}
    adminPasswordSecret:
      name: central-htpasswd
{{- end }}
    db:
      isEnabled: Enabled
{{- if gt (len .Values.centralDbPassword) 0 }}
      passwordSecret:
        name: central-db-password
{{- end }}
{{- if eq .Values.deploymentMode "dev" }}
      resources:
        limits:
          cpu: 4000m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 500Mi
{{- end }}
{{- if gt (len .Values.centralDefaultTlsCrt) 0 }}
    defaultTLSSecret:
      name: central-default-tls-cert
{{- end }}
    exposure:
      loadBalancer:
        enabled: false
        port: 443
      nodePort:
        enabled: false
      route:
        enabled: true
    monitoring:
      exposeEndpoint: Enabled
    persistence:
      persistentVolumeClaim:
        claimName: stackrox-db
{{- if eq .Values.deploymentMode "dev" }}
    resources:
      limits:
        cpu: 4000m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 500Mi
{{- end }}
  egress:
    connectivityPolicy: {{ .Values.centralConnectivityPolicy }}
  scanner:
    analyzer:
{{- if eq .Values.deploymentMode "dev" }}
      resources:
        limits:
          cpu: 4000m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 500Mi
{{- end }}
      scaling:
{{- if eq .Values.deploymentMode "dev" }}
        autoScaling: Disabled
        replicas: 1
{{- else }}
        autoScaling: Enabled
        maxReplicas: 5
        minReplicas: 2
        replicas: 3
{{- end }}
    scannerComponent: Enabled
  customize:
    {{- with .Values.annotations }}
    annotations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    envVars:
      # Log HTTP requests to the Central endpoint
      # A new environment variable for Central ROX_NETWORK_ACCESS_LOG, defaulted to false, is available.
      # When set to true, each network request to Central (via API, UI) is logged in the Central logs.
      # Note: When turned on, this environment variable will cause noisy logging, and hence should be turned on only for the
      # purpose of debugging network connectivity issues. Once network connectivity is established, we should advise
      # to immediately set this to false to stop logging.
      - name: ROX_NETWORK_ACCESS_LOG
        value: '{{ .Values.roxNetworkAccessLog }}'
      # Log gRPC requests to the Central endpoint
      - name: ROX_GRPC_ENABLE_REQUEST_TRACING
        value: '{{ .Values.roxGrpcEnableRequestTracing }}'
      # Set log level for Central. Allowed values are debug, info, ...
      - name: LOGLEVEL
        value: '{{ .Values.logLevel }}'
      - name: ROX_DISABLE_AUTOGENERATED_REGISTRIES
        value: '{{ .Values.roxDisableAutogeneratedRegistries }}'
{{- if gt (len .Values.additionalTrustedCa) 0 }}
  tls:
    additionalCAs:
      - name: custom_trusted_ca
        content: |
          {{- .Values.additionalTrustedCa | nindent 10 }}
{{- end }}
