apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: {{ .Release.Namespace }}
spec:
  managementState: Managed
{{- if .Values.forwardToLoki }}
  logStore:
    type: lokistack
    lokistack:
      name: loki
{{- end }}
  collection:
    type: vector
