{{- if .Values.forwardToSplunkEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: splunk-secret
  namespace: {{ .Release.Namespace }}
stringData:
  hecToken: '{{ .Values.splunkHecToken }}'
{{- end }}
