{{- range .Values.providers }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-creds
  namespace: openshift-mtv
stringData:
  insecureSkipVerify: {{ .insecureSkipVerify | toString | squote }}
  password: {{ .password | squote }}
  thumbprint: {{ .thumbprint }}
  url: {{ .url }}
  user: {{ .user }}
  cacert: |
    {{ .caCert| nindent 4 }}
{{- end }}
