# Persistent storage for Ceph mons can come from hostPath (typically used on bare metal
# clusters) or from a PVC (typically used on VMware and public cloud)
# If using hostPath volumes, remember to delete the /var/lib/rook directory on OpenShift nodes
# before redeploying the ODF cluster using: sudo rm -rf /var/lib/rook
useHostPathForMonDataDir: false
# Example storage class names: gp3-csi (AWS), thin-csi (VMware), openebs-lvm, lvms-loop1-vg
monPVCTemplate:
  storageClassName: gp3-csi
  storageCapacity: 50Gi
storageDeviceSets:
  storageClassName: gp3-csi
  storageCapacity: 2Ti
  count: 1
  replica: 3
# The default storageclass for NooBaa is ocs-storagecluster-ceph-rbd. This causes
# issues during ODF uninstallation. The storage cluster is being deleted while NooBaa
# still uses a PVC (db-noobaa-db-pg-0) provisioned from the storage cluster.
# This option allows setting the storageclass to something else like for example
# gp3-csi on AWS, so that the uninstallation of ODF doesn't get stuck.
multiCloudGateway:
  storageClassName: ''
# Enable cluster-wide storage encryption
# (this setting cannot be changed after the storage cluster was created)
encryptionClusterWide: false
# Enable KMS-based volume encryption
encryptionKmsEnable: false
# If the uninstall.ocs.openshift.io/cleanup-policy is set to "delete",
# the Rook-Ceph storage operator cleans up the physical drives and the DataDirHostPath.
# If the uninstall.ocs.openshift.io/cleanup-policy is set to "retain",
# it keeps the physical drives and DataDirHostPath.
# For production deployments, set uninstallCleanUpPolicy to "retain".
uninstallCleanUpPolicy: retain
# If the uninstall.ocs.openshift.io/mode is set to "graceful",
# the Rook-Ceph and NooBaa operators pause the uninstall process
# until the PVCs and OBCs are removed manually.
# If the uninstall.ocs.openshift.io/mode is set to "forced",
# the Rook-Ceph and NooBaa operators proceed with the uninstall process,
# even if the PVCs and the OBCs still exist.
# For production deployments, set uninstallMode to "graceful".
uninstallMode: graceful
