# Example storage class names: gp3-csi (AWS), thin-csi (VMware), openebs-lvm, lvms-loop1-vg
monPVCTemplate:
  storageClassName: gp3-csi
  storageCapacity: 50Gi
storageDeviceSets:
  storageClassName: gp3-csi
  storageCapacity: 2Ti
encryptionEnable: false
uninstallCleanUpPolicy: delete
uninstallMode: forced
